// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package errors

import (
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

const (
	Errors_ArticleTitleMissing   = "Article_ArticleTitleMissing"
	Errors_ArticleContentMissing = "Article_ArticleContentMissing"
)

func IsArticleTitleMissing(err error) bool {
	return errors.Reason(err) == Errors_ArticleTitleMissing
}

func IsArticleContentMissing(err error) bool {
	return errors.Reason(err) == Errors_ArticleContentMissing
}

const (
	Errors_CommentNameMissing    = "Comment_CommentNameMissing"
	Errors_CommentContentMissing = "Comment_CommentContentMissing"
)

func IsCommentNameMissing(err error) bool {
	return errors.Reason(err) == Errors_CommentNameMissing
}

func IsCommentContentMissing(err error) bool {
	return errors.Reason(err) == Errors_CommentContentMissing
}
